#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : synergy
Version  : 1.10.0.stable
Release  : 1
URL      : https://github.com/symless/synergy-core/archive/v1.10.0-stable.tar.gz
Source0  : https://github.com/symless/synergy-core/archive/v1.10.0-stable.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 OpenSSL
Requires: synergy-bin
Requires: synergy-data
Requires: synergy-license
BuildRequires : cmake
BuildRequires : libX11-dev
BuildRequires : libXtst-dev
BuildRequires : mesa-dev
BuildRequires : openssl-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras
Patch1: 0001-Use-target_link_libraries-instead-of-qt5_use_modules.patch
Patch2: 0002-Add-missing-header-includes-to-build-against-Qt-5.11.patch
Patch3: 0003-disable-zeroconf-and-dns_sd.patch

%description
Google C++ Testing Framework
============================
http://code.google.com/p/googletest/

%package bin
Summary: bin components for the synergy package.
Group: Binaries
Requires: synergy-data
Requires: synergy-license

%description bin
bin components for the synergy package.


%package data
Summary: data components for the synergy package.
Group: Data

%description data
data components for the synergy package.


%package doc
Summary: doc components for the synergy package.
Group: Documentation

%description doc
doc components for the synergy package.


%package license
Summary: license components for the synergy package.
Group: Default

%description license
license components for the synergy package.


%prep
%setup -q -n synergy-core-1.10.0-stable
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531171239
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib $(grep -v '^#' ../Build.properties | while read variable; do echo "-D${variable// /}"; done)
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1531171239
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/synergy
cp LICENSE %{buildroot}/usr/share/doc/synergy/LICENSE
cp src/gui/src/LicenseManager.h %{buildroot}/usr/share/doc/synergy/src_gui_src_LicenseManager.h
cp res/License.tex %{buildroot}/usr/share/doc/synergy/res_License.tex
cp res/License.rtf %{buildroot}/usr/share/doc/synergy/res_License.rtf
cp ext/openssl/LICENSE %{buildroot}/usr/share/doc/synergy/ext_openssl_LICENSE
cp ext/gtest/COPYING %{buildroot}/usr/share/doc/synergy/ext_gtest_COPYING
cp ext/gmock/COPYING %{buildroot}/usr/share/doc/synergy/ext_gmock_COPYING
cp ext/gmock/scripts/generator/COPYING %{buildroot}/usr/share/doc/synergy/ext_gmock_scripts_generator_COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/synergy
/usr/bin/synergyc
/usr/bin/synergys
/usr/bin/syntool

%files data
%defattr(-,root,root,-)
/usr/share/applications/synergy.desktop
/usr/share/icons/hicolor/scalable/apps/synergy.svg

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/synergy/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/synergy/LICENSE
/usr/share/doc/synergy/ext_gmock_COPYING
/usr/share/doc/synergy/ext_gmock_scripts_generator_COPYING
/usr/share/doc/synergy/ext_gtest_COPYING
/usr/share/doc/synergy/ext_openssl_LICENSE
