#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : synergy
Version  : 1.11.1
Release  : 11
URL      : https://github.com/symless/synergy-core/archive/v1.11.1-stable/synergy-core-1.11.1.tar.gz
Source0  : https://github.com/symless/synergy-core/archive/v1.11.1-stable/synergy-core-1.11.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 OpenSSL
Requires: synergy-bin = %{version}-%{release}
Requires: synergy-data = %{version}-%{release}
Requires: synergy-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : glibc-dev
BuildRequires : libX11-dev
BuildRequires : libXtst-dev
BuildRequires : mesa-dev
BuildRequires : openssl-dev
BuildRequires : python3
BuildRequires : qttools-dev
Patch1: 0001-Use-target_link_libraries-instead-of-qt5_use_modules.patch
Patch2: 0002-disable-zeroconf-and-dns_sd.patch

%description
Google C++ Testing Framework
============================
http://code.google.com/p/googletest/

%package bin
Summary: bin components for the synergy package.
Group: Binaries
Requires: synergy-data = %{version}-%{release}
Requires: synergy-license = %{version}-%{release}

%description bin
bin components for the synergy package.


%package data
Summary: data components for the synergy package.
Group: Data

%description data
data components for the synergy package.


%package license
Summary: license components for the synergy package.
Group: Default

%description license
license components for the synergy package.


%prep
%setup -q -n synergy-core-1.11.1-stable
cd %{_builddir}/synergy-core-1.11.1-stable
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584642797
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. $(grep -v '^#' ../Build.properties | while read variable; do echo "-D${variable// /}"; done)
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1584642797
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/synergy
cp %{_builddir}/synergy-core-1.11.1-stable/LICENSE %{buildroot}/usr/share/package-licenses/synergy/395b7e59bf458e5fc394dfda946d656126941f64
cp %{_builddir}/synergy-core-1.11.1-stable/ext/gmock/COPYING %{buildroot}/usr/share/package-licenses/synergy/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/synergy-core-1.11.1-stable/ext/gmock/scripts/generator/COPYING %{buildroot}/usr/share/package-licenses/synergy/1d4719e04eaa4909ab5a59ef5cb04d2a5517716e
cp %{_builddir}/synergy-core-1.11.1-stable/ext/gtest/COPYING %{buildroot}/usr/share/package-licenses/synergy/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/synergy-core-1.11.1-stable/ext/openssl/LICENSE %{buildroot}/usr/share/package-licenses/synergy/102073b66c9be39953f62af2eb238629f7d50883
cp %{_builddir}/synergy-core-1.11.1-stable/res/License.rtf %{buildroot}/usr/share/package-licenses/synergy/f801798afe701ce87c20062a6a514d1ab7bf5185
cp %{_builddir}/synergy-core-1.11.1-stable/res/License.tex %{buildroot}/usr/share/package-licenses/synergy/28c8b9f7de43754bf7dfa7ddef3dabd54d257cd2
cp %{_builddir}/synergy-core-1.11.1-stable/src/gui/src/LicenseManager.h %{buildroot}/usr/share/package-licenses/synergy/5f01e0463f52128dc17daa4114a7f4cf0633e31d
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/share/package-licenses/synergy/src_gui_src_LicenseManager.h

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/synergy
/usr/bin/synergyc
/usr/bin/synergys
/usr/bin/syntool

%files data
%defattr(-,root,root,-)
/usr/share/applications/synergy.desktop
/usr/share/icons/hicolor/scalable/apps/synergy.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/synergy/102073b66c9be39953f62af2eb238629f7d50883
/usr/share/package-licenses/synergy/1d4719e04eaa4909ab5a59ef5cb04d2a5517716e
/usr/share/package-licenses/synergy/28c8b9f7de43754bf7dfa7ddef3dabd54d257cd2
/usr/share/package-licenses/synergy/395b7e59bf458e5fc394dfda946d656126941f64
/usr/share/package-licenses/synergy/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/synergy/5f01e0463f52128dc17daa4114a7f4cf0633e31d
/usr/share/package-licenses/synergy/f801798afe701ce87c20062a6a514d1ab7bf5185
